### ISSUE TITLE
Lazy loading of images does not work in visibility examples page

### ISSUE THREAD

**Issue by furins** [Semantic-Org/Semantic-UI#2127]
Hello, 
first of all I'd like to thank you for this gorgeous UI framework!
I've noticed a minor issue in docs:

opening http://semantic-ui.com/behaviors/visibility.html#/examples with Chrome 41 does not lazy load images.
The error (`Uncaught TypeError: undefined is not a function`) seems related to the absence of a `m.precache` function. 
Since I'm not able to reproduce the error with the latest semantic-ui library on my computer (it just works fine) I guess it's just a problem with the  minified version of the library linked by the page.

**Comment by DHNCarlos** [comment]
Lazy load itself seems to work fine on Firefox Developer Edition 39.0a2 when viewing it in SUI docs but also gives the same error in console: `TypeError: m.precache is not a function`.

**Comment by jlukic** [comment]
Ill have to take a look, sorry I've been juggling these two release channels and there might be some issues with what I deployed.

**Comment by jlukic** [comment]
Somehow precache got cut in https://github.com/Semantic-Org/Semantic-UI/commit/fad2d1b57c6247d1da9cdc6678005dc04ff5e413

Porting visibility from `2.x` to `1.x` channel.

**Comment by jlukic** [comment]
Releasing `1.12.0` now with fix

**Comment by jlukic** [comment]
http://semantic-ui.com/behaviors/visibility.html#/examples
Fix live
