### ISSUE TITLE
npm install -> gulp install error

### ISSUE THREAD

**Issue by abbiento** [Semantic-Org/Semantic-UI#4727]
I used the command npm install --save semantic-ui but after some download I receive this error in the file error.png. I've attached npm-debug.txt. How can I resolve the problem?

[npm-debug.txt](https://github.com/Semantic-Org/Semantic-UI/files/581307/npm-debug.txt)

![error](https://cloud.githubusercontent.com/assets/6938151/20145458/7def49ba-a6a0-11e6-853a-ab0b449ca16d.png)

**Comment by webdesignberlin** [comment]
Hi.

I've tried to track down your problem. No problems with Windows 10, Windows 7 with node v4.6.1 and Gulp CLI version 1.2.2 and Gulp Local version 3.9.1.

Which Gulp and Node version do you use?

Best regards, Micha

**Comment by wolfadex** [comment]
I'm on Ubuntu 14.04, node 6.6.0, Gulp CLI version 1.2.2 and Gulp Local version 3.9.1.

Could it be an issue with [accord](https://github.com/jescalan/accord)? I noticed that is the module that's throwing the error and on their github page their current build is failing.

**Comment by wolfadex** [comment]
Also of note, this issue doesn't occur with bower.

**Comment by abbiento** [comment]
Gulp CLI global, version 3.9.1
Npm global, version 3.10.9

I should ever install a local version of gulp? When I've tried to install gulp locally (same version 3.9.1) I've got the same error..

**Comment by abbiento** [comment]
This are step for semantic-ui installation on my windows 10:
1) md sui
2) npm init (with all default)
3) npm install --save-dev gulp
4) npm install --save semantic-ui

and this is the error:

![error](https://cloud.githubusercontent.com/assets/6938151/20208466/ac9fd87a-a7ee-11e6-9c11-95fb1ac89384.png)

**Comment by abbiento** [comment]
No resolution??

**Comment by liam-cameron** [comment]
+1 exact same issue

**Comment by liam-cameron** [comment]
Liams-MBP:project liamcameron$ npm install semantic-ui
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global js-beautify@1.5.10 should be installed with -g

> semantic-ui@2.2.6 install /Users/liamcameron/project/node_modules/semantic-ui
> gulp install

[13:31:48] Using gulpfile ~/project/node_modules/semantic-ui/gulpfile.js
[13:31:48] Starting 'install'...
[13:31:51] 'install' errored after 2.69 s
[13:31:51] TypeError: gulp.hasTask is not a function
    at /Users/liamcameron/project/node_modules/run-sequence/index.js:19:22
    at Array.forEach (native)
    at verifyTaskSets (/Users/liamcameron/project/node_modules/run-sequence/index.js:13:11)
    at runSequence (/Users/liamcameron/project/node_modules/run-sequence/index.js:92:2)
    at Gulp.module.exports (/Users/liamcameron/project/node_modules/semantic-ui/tasks/install.js:450:1)
    at module.exports (/Users/liamcameron/project/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/liamcameron/project/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/liamcameron/project /node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/liamcameron/project/node_modules/orchestrator/index.js:134:8)
    at /Users/liamcameron/project/node_modules/semantic-ui/node_modules/gulp/bin/gulp.js:129:20
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN project No description
npm WARN project No repository field.
npm WARN project No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/liamcameron/.npm-packages/bin/npm" "install" "semantic-ui"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.2.6 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.2.6 install script 'gulp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/liamcameron/project/npm-debug.log

Liams-MBP:project liamcameron$ npm -v
3.10.8
Liams-MBP:project liamcameron$ node -v
v6.7.0
Liams-MBP:project liamcameron$ gulp -v
[13:58:58] CLI version 1.2.2
[13:58:58] Local version 4.0.0-alpha.2

**Comment by liam-cameron** [comment]
Upgraded gulp version, still receive error.

Liams-MBP:project liamcameron$ gulp -v
[14:01:41] CLI version 3.9.1
[14:01:42] Local version 4.0.0-alpha.2

**Comment by abbiento** [comment]
Cool, i'm not alone.. No one have a solution?

**Comment by ludo237** [comment]
I've the same issue

Node -v `v7.1.0`

Npm -v  `3.10.9`

Gulp -v 
```
CLI version 3.9.1
Local version 3.9.1
```

**Comment by camnuckols** [comment]
Same problem. Haven't found a solution so far.

**Comment by Shashwatsh** [comment]
works with 7.2

**Comment by jedabero** [comment]
If anyone encounters this problem while using GIT BASH, just use widows terminal.
I was able to install semantic on 
 - Windows 8.1, node 6.9.5, npm 3.10.10
 - WIndows 7, node 7.9.0, npm 4.2.0

In both cases, when using GIT BASH, I got errors similar to liam-cameron and abbiento

**Comment by geomorillo** [comment]
im still having this issue

**Comment by zmechanic** [comment]
I got it working by running all dependent packages under version specific gulp install:

    npm install gulp@3.9.1 sparkles duplexify ansi-colors path-dirname semantic-ui --save

You might need to add more packages in a sequence if `npm` complains.

**Comment by coder8keyboard** [comment]
npm install gulp@3.9.1 semantic-ui --save worked for me for semantic-ui installation.
However, my Aurelia build required gulp 4. So I had to install version 4 again.

**Comment by bArraxas** [comment]
I have the same problem :

> TypeError: gulp.hasTask is not a function
    at C:\wamp64\www\blog\node_modules\run-sequence\index.js:23:22
...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I use :
- windows 7
- npm@11.2
- gulp@3.9.1
- semantic-ui@2.4.2

**Comment by bArraxas** [comment]
Problem solved !
Dont let the default directory (project folder) simply specify the node_modules folder and it will be okay nevermore the configuration.

**Comment by neel** [comment]
Prroblem persists Arch Linux

```
> semantic-ui@2.4.2 install /home/neel/Projects/byakaran/web/packed/node_modules/semantic-ui
> gulp install

[16:57:30] Using gulpfile ~/Projects/byakaran/web/packed/node_modules/semantic-ui/gulpfile.js
[16:57:30] Starting 'install'...
[16:57:30] 'install' errored after 34 ms
[16:57:30] TypeError: gulp.hasTask is not a function
    at /home/neel/Projects/byakaran/web/packed/node_modules/run-sequence/index.js:23:22
    at Array.forEach (<anonymous>)
    at verifyTaskSets (/home/neel/Projects/byakaran/web/packed/node_modules/run-sequence/index.js:17:11)
    at runSequence (/home/neel/Projects/byakaran/web/packed/node_modules/run-sequence/index.js:130:2)
    at Gulp.module.exports (/home/neel/Projects/byakaran/web/packed/node_modules/semantic-ui/tasks/install.js:452:1)
    at module.exports (/home/neel/Projects/byakaran/web/packed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/neel/Projects/byakaran/web/packed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/neel/Projects/byakaran/web/packed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/neel/Projects/byakaran/web/packed/node_modules/orchestrator/index.js:134:8)
    at /home/neel/Projects/byakaran/web/packed/node_modules/semantic-ui/node_modules/gulp/bin/gulp.js:129:20
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/neel/.npm/_logs/2019-07-15T11_27_31_113Z-debug.log
[neel@archlinux packed]$ gulp -v
bash: gulp: command not found
[neel@archlinux packed]$ npx gulp -v
CLI version: 2.2.0
Local version: 4.0.2

```

**Comment by nshore** [comment]
Thanks @bArraxas lost a few hours trying to work this out

**Comment by mohameedf** [comment]
same problem

**Comment by jmagill-platinumplatypus** [comment]
I'm not sure exactly what @bArraxas is recommend. Can someone help explain?

**Comment by bArraxas** [comment]
Hi jmagill-platinumplatypus, in my case it's the second part of installation who fail.
In the second step of installation, the terminal ask us some questions.
And then, I said :

> Dont let the default directory (project folder) simply specify the node_modules folder and it will be okay

**Comment by jmagill-platinumplatypus** [comment]
@bArraxas That makes sense. Thanks!

**Comment by danShumway** [comment]
Are there any plans to fix this in the next release? A group I'm working with is currently running into this problem. If the repository isn't being maintained any more at this point, it would be good to know so we can vendor the dependency and start applying our own patches.

**Comment by lubber-de** [comment]
@danShumway Try the active community fork https://fomantic-ui.com

**Comment by NoNameNamer** [comment]
Migrating from Azure to Cloudflare Pages surfaced this issue for me as well.
